# Generated by Django 4.2.2 on 2023-06-29 00:33

import api_agro.models.user
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='product/', verbose_name='Foto')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição do Produto')),
                ('value', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, error_messages={'unique': 'Nome já Existe!'}, max_length=70, null=True, unique=True, verbose_name='Nome Completo')),
                ('profile', models.ImageField(blank=True, default='profile/not_user.jpg', null=True, upload_to='profile/', verbose_name='Foto de Perfil')),
                ('email', models.EmailField(error_messages={'unique': 'E-mail já Cadastrado!'}, max_length=200, unique=True, verbose_name='E-mail')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de Telefone')),
                ('link_intagram', models.URLField(blank=True, null=True, verbose_name='Link do Whatsapp')),
                ('link_optional', models.URLField(blank=True, null=True, verbose_name='Outros Link de Rede Social')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
            },
            managers=[
                ('objects', api_agro.models.user.UserManager()),
            ],
        ),
    ]
