# Generated by Django 4.2.2 on 2023-07-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agro', '0004_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Foto'),
        ),
    ]
