# Generated by Django 4.2.2 on 2023-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agro', '0005_alter_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ImageField(blank=True, default='product/auto.png', null=True, upload_to='product/', verbose_name='Foto'),
        ),
    ]
